### ISSUE TITLE
App crashed when press back after enter card detail

### ISSUE THREAD

**Issue by kukadiyaAni** [wgltony/react-native-braintree-dropin-ui#120]
I have updated latest version and while testing I saw one crashed

Step
1. Click on Credit or Debit Card
2. Enter the card number after entering the card number click on Next
3. Show the expiration date and CVV field if click on back on this app will be crashed

Please help me here and let me know if I did something wrong

here is log

```
PID: 27707
java.lang.NullPointerException: Attempt to invoke virtual method 'android.os.Parcelable android.os.Bundle.getParcelable(java.lang.String)' on a null object reference
at com.braintreepayments.api.AddCardFragment.onCreateView(AddCardFragment.java:59)
at androidx.fragment.app.Fragment.performCreateView(Fragment.java:3113)
at androidx.fragment.app.FragmentStateManager.createView(FragmentStateManager.java:524)
at androidx.fragment.app.FragmentStateManager.moveToExpectedState(FragmentStateManager.java:261)
at androidx.fragment.app.FragmentManager.executeOpsTogether(FragmentManager.java:1892)
at androidx.fragment.app.FragmentManager.removeRedundantOperationsAndExecute(FragmentManager.java:1819)
at androidx.fragment.app.FragmentManager.execPendingActions(FragmentManager.java:1762)
at androidx.fragment.app.FragmentManager$5.run(FragmentManager.java:547)
at android.os.Handler.handleCallback(Handler.java:958)
at android.os.Handler.dispatchMessage(Handler.java:99)
at android.os.Looper.loopOnce(Looper.java:205)
at android.os.Looper.loop(Looper.java:294)
at android.app.ActivityThread.main(ActivityThread.java:8177)
at java.lang.reflect.Method.invoke(Native Method)
at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:552)
at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:971)
```

![Screenshot 2023-12-18 at 5 15 33 PM](https://github.com/wgltony/react-native-braintree-dropin-ui/assets/16218216/dd374e58-b881-40ea-97f0-ece48fb3649d)

**Comment by Kowshika-aspire** [comment]
Facing same issue. Any updates ?

**Comment by Kowshika-aspire** [comment]
@kukadiyaAni Did you fixed this issue ?

**Comment by Kowshika-aspire** [comment]
Any updates on this issue..?
